dataset_name: "Higgs small"
target_col: "target"
csv_path: "data/higgs_small.csv" 

num_cols:
  - "lepton_pT"
  - "lepton_eta"
  - "lepton_phi"
  - "missing_energy_magnitude"
  - "missing_energy_phi"
  - "jet1pt"
  - "jet1eta"
  - "jet1phi"
  - "jet1b-tag"
  - "jet2pt"
  - "jet2eta"
  - "jet2phi"
  - "jet2b-tag"
  - "jet3pt"
  - "jet3eta"
  - "jet3phi"  
  - "jet3b-tag"
  - "jet4pt"
  - "jet4eta"
  - "jet4phi"
  - "jet4b-tag"
  - "m_jj"
  - "m_jjj"
  - "m_lv" 
  - "m_jlv"
  - "m_bb"
  - "m_wbb"
  - "m_wwbb" 
  # ...
cat_cols: []

