dataset_name: "MIMIC-IV Mortality"
target_col: "mortality"
csv_path: "data/mimic4.csv"

num_cols:
  - "Diastolic blood pressure"
  - "Fraction inspired oxygen"
  - "Glascow coma scale eye opening"
  - "Glascow coma scale motor response"
  - "Glascow coma scale total"
  - "Glascow coma scale verbal response"
  - "Glucose"
  - "Heart Rate"
  - "Height"
  - "Mean blood pressure"
  - "Oxygen saturation"
  - "Respiratory rate"
  - "Systolic blood pressure"
  - "Temperature"
  - "Weight"
  - "pH"

cat_cols:
  - "Capillary refill rate"