dataset_name: "NHANES"
target_col: "target"
csv_path: "data/nhanes.csv"

num_cols:
  - "age"
  - "physical_activity"
  - "serum_albumin"
  - "alkaline_phosphatase"
  - "SGOT"
  - "BUN"
  - "calcium"
  - "creatinine"
  - "potassium"
  - "sodium"
  - "total_bilirubin"
  - "serum_protein"
  - "red_blood_cells"
  - "white_blood_cells"
  - "hemoglobin"
  - "hematocrit"
  - "segmented_neutrophils"
  - "lymphocytes"
  - "monocytes"
  - "eosinophils"
  - "basophils"
  - "band_neutrophils"
  - "cholesterol"
  - "urine_pH"
  - "sedimentation_rate"
  - "uric_acid"
  - "systolic_blood_pressure"
  - "pulse_pressure"
  - "bmi"

# 범주형 피처 (총 50개)
# 성별 및 결측/상태를 나타내는 Boolean 플래그들입니다.
cat_cols:
  - "sex_isFemale"
  - "alkaline_phosphatase_isUnacceptable"
  - "alkaline_phosphatase_isTestnotdone"
  - "SGOT_isUnacceptable"
  - "SGOT_isTestnotdone"
  - "BUN_isUnacceptable"
  - "BUN_isTestnotdone"
  - "calcium_isUnacceptable"
  - "calcium_isTestnotdone"
  - "creatinine_isUnacceptable"
  - "creatinine_isTestnotdone"
  - "potassium_isUnacceptable"
  - "sodium_isUnacceptable"
  - "total_bilirubin_isUnacceptable"
  - "total_bilirubin_isTestnotdone"
  - "red_blood_cells_isUnacceptable"
  - "red_blood_cells_isBlankbutapplicable"
  - "white_blood_cells_isUnacceptable"
  - "white_blood_cells_isBlankbutapplicable"
  - "hemoglobin_isMissing"
  - "hematocrit_isUnacceptable"
  - "hematocrit_isMissing"
  - "platelets_isNormal"
  - "platelets_isIncreased"
  - "platelets_isDecreased"
  - "platelets_isNoestimate"
  - "cholesterol_isMissing"
  - "urine_albumin_isNegative"
  - "urine_albumin_is>=30"
  - "urine_albumin_is>=100"
  - "urine_albumin_is>=300"
  - "urine_albumin_is>=1000"
  - "urine_albumin_isTrace"
  - "urine_albumin_isBlankbutapplicable"
  - "urine_glucose_isNegative"
  - "urine_glucose_isLight"
  - "urine_glucose_isMedium"
  - "urine_glucose_isDark"
  - "urine_glucose_isVerydark"
  - "urine_glucose_isTrace"
  - "urine_glucose_isBlankbutapplicable"
  - "urine_pH_isBlankbutapplicable"
  - "urine_hematest_isNegative"
  - "urine_hematest_isSmall"
  - "urine_hematest_isModerate"
  - "urine_hematest_isLarge"
  - "urine_hematest_isBlankbutapplicable"
  - "sedimentation_rate_isBlankbutapplicable"
  - "uric_acid_isUnacceptable"
  - "uric_acid_isTestnotdone"
