dataset_name: "YearPredication"
target_col: "year"
csv_path: "data/year_prediction.csv" 

num_cols:
  - "timbre_1"  
  - "timbre_2"
  - "timbre_3"
  - "timbre_4"
  - "timbre_5"
  - "timbre_6"
  - "timbre_7"
  - "timbre_8"
  - "timbre_9"
  - "timbre_10"
  - "timbre_11"  
  - "timbre_12"
  - "timbre_13"
  - "timbre_14"
  - "timbre_15"
  - "timbre_16"
  - "timbre_17"
  - "timbre_18"
  - "timbre_19"
  - "timbre_20"
  - "timbre_21"  
  - "timbre_22"
  - "timbre_23"
  - "timbre_24"
  - "timbre_25"
  - "timbre_26"
  - "timbre_27"
  - "timbre_28"
  - "timbre_29"  
  - "timbre_30"
  - "timbre_31"  
  - "timbre_32"
  - "timbre_33"
  - "timbre_34"
  - "timbre_35"
  - "timbre_36"
  - "timbre_37"
  - "timbre_38"
  - "timbre_39"
  - "timbre_40"
  - "timbre_41"  
  - "timbre_42"
  - "timbre_43"
  - "timbre_44"
  - "timbre_45"
  - "timbre_46"
  - "timbre_47"
  - "timbre_48"
  - "timbre_49"
  - "timbre_50"
  - "timbre_51"  
  - "timbre_52"
  - "timbre_53"
  - "timbre_54"
  - "timbre_55"
  - "timbre_56"
  - "timbre_57"
  - "timbre_58"
  - "timbre_59"
  - "timbre_60"
  - "timbre_61"  
  - "timbre_62"
  - "timbre_63"
  - "timbre_64"
  - "timbre_65"
  - "timbre_66"
  - "timbre_67"
  - "timbre_68"
  - "timbre_69"
  - "timbre_70"
  - "timbre_71"  
  - "timbre_72"
  - "timbre_73"
  - "timbre_74"
  - "timbre_75"
  - "timbre_76"
  - "timbre_77"
  - "timbre_78"
  - "timbre_79"
  - "timbre_80"
  - "timbre_81"  
  - "timbre_82"
  - "timbre_83"
  - "timbre_84"
  - "timbre_85"
  - "timbre_86"
  - "timbre_87"
  - "timbre_88"
  - "timbre_89"
  - "timbre_90"
  # ...
cat_cols: []

