# Source: TabM Appendix D.12 (Standard Tuning Protocol)
# [Shared Structure]
n_layers: # blocks
  type: "int"
  low: 1
  high: 4

d_token: # Embedding Size
  type: "int"
  low: 16
  high: 384
  step: 16

# [Shared Optimization]
learning_rate:
  type: "float"
  low: 3e-5
  high: 1e-3
  log: true

weight_decay:
  type: "float"
  low: 1e-4
  high: 1e-1
  log: true

# [FT-Specific & Regularization]
attention_dropout:
  type: "float"
  low: 0.0
  high: 0.5

ffn_dropout:
  type: "float"
  low: 0.0
  high: 0.5

residual_dropout:
  type: "float"
  low: 0.0
  high: 0.2

d_ff_factor:
  type: "float"
  low: 0.66
  high: 2.66